// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package main

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type document_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var DocumentBinding = document_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 4008946543815553422,
}

// Document_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Document_ = struct {
	Id        *objectbox.PropertyUint64
	Text      *objectbox.PropertyString
	Embedding *objectbox.PropertyByteVector
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &DocumentBinding.Entity,
		},
	},
	Text: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &DocumentBinding.Entity,
		},
	},
	Embedding: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &DocumentBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (document_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (document_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Document", 1, 4008946543815553422)
	model.Property("Id", 6, 1, 5103350790757329386)
	model.PropertyFlags(1)
	model.Property("Text", 9, 2, 1795757088449978332)
	model.Property("Embedding", 23, 3, 2683045624018826083)
	model.EntityLastPropertyId(3, 2683045624018826083)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (document_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Document).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (document_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Document).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (document_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (document_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Document)
	var offsetText = fbutils.CreateStringOffset(fbb, obj.Text)
	var offsetEmbedding = fbutils.CreateByteVectorOffset(fbb, obj.Embedding)

	// build the FlatBuffers object
	fbb.StartObject(3)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetText)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetEmbedding)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (document_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Document' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &Document{
		Id:        propId,
		Text:      fbutils.GetStringSlot(table, 6),
		Embedding: fbutils.GetByteVectorSlot(table, 8),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (document_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Document, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (document_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Document), nil)
	}
	return append(slice.([]*Document), object.(*Document))
}

// Box provides CRUD access to Document objects
type DocumentBox struct {
	*objectbox.Box
}

// BoxForDocument opens a box of Document objects
func BoxForDocument(ob *objectbox.ObjectBox) *DocumentBox {
	return &DocumentBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Document.Id property on the passed object will be assigned the new ID as well.
func (box *DocumentBox) Put(object *Document) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Document.Id property on the passed object will be assigned the new ID as well.
func (box *DocumentBox) Insert(object *Document) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *DocumentBox) Update(object *Document) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *DocumentBox) PutAsync(object *Document) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Document.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Document.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *DocumentBox) PutMany(objects []*Document) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *DocumentBox) Get(id uint64) (*Document, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Document), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *DocumentBox) GetMany(ids ...uint64) ([]*Document, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Document), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *DocumentBox) GetManyExisting(ids ...uint64) ([]*Document, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Document), nil
}

// GetAll reads all stored objects
func (box *DocumentBox) GetAll() ([]*Document, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Document), nil
}

// Remove deletes a single object
func (box *DocumentBox) Remove(object *Document) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *DocumentBox) RemoveMany(objects ...*Document) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Document_ struct to create conditions.
// Keep the *DocumentQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *DocumentBox) Query(conditions ...objectbox.Condition) *DocumentQuery {
	return &DocumentQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Document_ struct to create conditions.
// Keep the *DocumentQuery if you intend to execute the query multiple times.
func (box *DocumentBox) QueryOrError(conditions ...objectbox.Condition) (*DocumentQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &DocumentQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See DocumentAsyncBox for more information.
func (box *DocumentBox) Async() *DocumentAsyncBox {
	return &DocumentAsyncBox{AsyncBox: box.Box.Async()}
}

// DocumentAsyncBox provides asynchronous operations on Document objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type DocumentAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForDocument creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use DocumentBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForDocument(ob *objectbox.ObjectBox, timeoutMs uint64) *DocumentAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &DocumentAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *DocumentAsyncBox) Put(object *Document) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *DocumentAsyncBox) Insert(object *Document) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *DocumentAsyncBox) Update(object *Document) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *DocumentAsyncBox) Remove(object *Document) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Document which Id is either 42 or 47:
//
// box.Query(Document_.Id.In(42, 47)).Find()
type DocumentQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *DocumentQuery) Find() ([]*Document, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Document), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *DocumentQuery) Offset(offset uint64) *DocumentQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *DocumentQuery) Limit(limit uint64) *DocumentQuery {
	query.Query.Limit(limit)
	return query
}
